version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python app.py runserver 0.0.0.0:8000"
      sh -c "python request.py migrate"
